### ISSUE TITLE
Can this specify standard `serviceType` codes?

### ISSUE THREAD

**Issue by Mr0grog** [smart-on-fhir/smart-scheduling-links#10]
In the schedule section of the spec, the information around `serviceType` suggests that the example “*can* be used verbatim,” but doesn’t mandate any particular formats or codes. It also points to the FHIR docs for [CodeableConcept](http://hl7.org/fhir/datatypes.html#codeableconcept) for specifics.

It reads to me like a provider might be free to use whatever codings fit their existing system. I am currently working on COVID response tech for state governments, and it would be nice to be able to mandate at least:
- That the provider use the object-based `coding` field for each service type (and MAY use `text` in addition).
- That a COVID-19 immunization uses the coding:

    ```json
    {
      "system": "http://fhir-registry.smarthealthit.org/CodeSystem/service-type",
      "code": "covid19-immunization",
      "display": "COVID-19 Immunization Appointment"
    }
    ```

    …from the example. (Optionally in addition to any other more local codings they choose.) This would help us have an actual, standardized way to identify these kinds of appointments across providers, which we do not currently have.

    I’m also not clear on whether that example is an actual, defined code anywhere (HL7 and FHIR are reasonably new to me, so I am almost certainly missing where information on what the `http://fhir-registry.smarthealthit.org/CodeSystem/service-type` system defines can be found — I’d appreciate any links to what I should be reading!).

**Comment by jmandel** [comment]
Thanks, this is a great point. I'll add a clarification that for COVID-19 immunization slots, the `coding` array needs to include the two specified values and *MAY* include additional Codings.

`http://fhir-registry.smarthealthit.org` is an identifier we use for standardized extensions and codings published by SMART Health IT; there's no published content at that domain (so indeed, if you de-reference it by, say, pasting it into a browser window, you won't find any definitions; that's something we might introduce, but shouldn't be a requirement for interop).
