### ISSUE TITLE
Handling inexact counts?

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/smart-scheduling-links#19]
Comment from [Zulip chat](https://chat.fhir.org/#narrow/stream/281612-smart.2Fscheduling-links/topic/Capacity.20when.20slot.20is.20busy/near/230868218): 

>Our preference was to publish a relative level of available slots such as "available, limited or none" as trying to publish accurate, meaningful numbers introduces a variety of challenges.

Josh's perspective: If it's useful to define an additional extension for concepts like limited versus somewhat limited versus lots of capacity we can do it, but I worry that interpreting these values would be difficult in the context of different sites (say, for small clinics vs mass vaccination sites).

**If we instead said that slot capacity could be populated with a best effort estimation, would this be an improvement?**

**Comment by hemalathar84** [comment]
The capacity information is very fluid and hard to send it. CVS is planning to send available or fully booked for slot availability

**Comment by jmandel** [comment]
To clarify, how is CVS planning to send "available or fully booked" using SMART Scheduling Links? Is this based on some combination of Slots and capacities?

**Comment by hemalathar84** [comment]
CVS is planning to publish the data via the file format and it is based on the combination of vaccine inventory, slots, and capacity.

**Comment by hemalathar84** [comment]
Josh, also a question on how CDC can get the files (Location, schedule, and Slot). Can CDC/consuming application share the IP's that will be used to pull the file so that we can whitelist?

**Comment by jmandel** [comment]
Re: access control, it's probably worth creating a separate issue if we want to specify something --  created #20 to this effect.

**Comment by jmandel** [comment]
> CVS is planning to publish the data via the file format

Just to check: I think this means you've got what you need between Schedule, Slot, and "capacity" extensions?

**Comment by hemalathar84** [comment]
Yes we got for Location, Schedule and Slot. We are not planning to send capacity extenstion and will add it to backlog. We can share some sample files to make sure we covered it all.

**Comment by jmandel** [comment]
OK, that's great, and sample files would be most helpful.

To be clear on the semantics of Slots: a single Slot with no capacity extension means "this schedule can accommodate one single patient." To advertise wider appointment availability, you'd want to publish multiple slots _or_ populate a capacity extension. If we can update the docs to help here (e.g., to specify that capacity is estimated or best-effort or even a bets guess), we'd be open to this.
