### ISSUE TITLE
Location example identifier has incorrect property names

### ISSUE THREAD

**Issue by cooperthompson** [smart-on-fhir/smart-scheduling-links#9]
The in-line example has identifier.url and identifier.valueString. I think these should be identifier.system and identifier.value.

  "identifier": [{
    "url": "https://cdc.gov/vaccines/programs/vtrcks",
    "valueString": "CV1654321"
  }],

**Comment by jmandel** [comment]
Thanks! (PRs are welcome BTW -- I mean, at your preference!)
